name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cocogitto
        uses: actions-rs/install@v0.1
        with:
          crate: cocogitto
          version: latest
      - name: Generate changelog
        run: cog changelog --at ${{ github.ref_name }} -t full_hash > CHANGELOG.md
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes-file CHANGELOG.md \
            --repo EgorHenek/ai-commit

  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../ai-commit-${{ matrix.target }}.zip ai-commit.exe
          else
            tar czvf ../../../ai-commit-${{ matrix.target }}.tar.gz ai-commit
          fi
          cd -
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            gh release upload ${{ github.ref_name }} ai-commit-${{ matrix.target }}.zip --repo EgorHenek/ai-commit
          else
            gh release upload ${{ github.ref_name }} ai-commit-${{ matrix.target }}.tar.gz --repo EgorHenek/ai-commit
          fi
